source 'https://rubygems.org'

gem "sinatra"
gem "sinatra-contrib"
gem "json"
gem "less"
gem "sprockets"
gem "coffee-script"
gem "rack-cache", "~> 1.2"
gem 'emk-sinatra-url-for'
gem 'handlebars_assets'

# for proper time zone handling
gem 'tzinfo' 

# js execution in Ruby
gem 'execjs'
gem 'therubyrhino'

group :development do
  # local execution
  gem 'trinidad'
  gem 'trinidad_daemon_extension'

  # for packaging
  gem 'warbler'
end